In [1]:
#import library

import pickle
import json
import pandas as pd
import numpy as np

In [2]:
#Load model

with open('list_cat_cols.txt', 'r') as file_1:
  list_cat_col = json.load(file_1)

with open('list_num_cols.txt', 'r') as file_2:
  list_num_col = json.load(file_2)

with open('encoder.pkl', 'rb') as file_3:
  model_encoder = pickle.load(file_3)

with open('scaler.pkl', 'rb') as file_4:
  model_scaler = pickle.load(file_4)

with open('model_lin_reg.pkl', 'rb') as file_5:
  model_log_reg = pickle.load(file_5)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator OrdinalEncoder from version 1.5.2 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator MinMaxScaler from version 1.5.2 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.5.2 when using version 1.6.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [3]:
data_inf = {
    'buying' : 0,
    'time_on_site' : 25,
    'pageviews' : 1.0,
    'latest_ecommerce_progress' : '0',
    'bounces' : '0',
    'medium' : 'referral',
    'channelGrouping' : 'Social',
    'deviceCategory' : 'mobile'
}

data_inf = pd.DataFrame([data_inf])
data_inf

,buying,time_on_site,pageviews,latest_ecommerce_progress,bounces,medium,channelGrouping,deviceCategory
0,0,25,1.0,0,0,referral,Social,mobile

In [4]:
#Split data numerik dan kategorik

data_inf_num = data_inf[list_num_col]
data_inf_cat = data_inf[list_cat_col]
data_inf_num

   time_on_site  pageviews
0            25        1.0

In [5]:
# Feature scaling and encoding

data_inf_num_scaled = model_scaler.fit_transform(data_inf_num)
data_inf_cat_encoded = model_encoder.fit_transform(data_inf_cat)
data_inf_final = np.concatenate([data_inf_num_scaled, data_inf_cat_encoded], axis = 1)

In [ ]:
# Prediksi menggunakan nilai Regresi Logistik
y_pred_inf = model_log_reg.predict(data_inf_final)
y_pred_inf